apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-service-config
  labels:
    app: notifications-service
data:
  SPRING_PROFILES_ACTIVE: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "notif_db"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8080"
  KEYCLOAK_REALM: "bookinghub"
  SMTP_HOST: "smtp"
  SMTP_PORT: "587"
  SMTP_AUTH: "true"
  SMTP_STARTTLS: "true"
  NOTIFICATIONS_FROM_EMAIL: "noreply@bookinghub.com"
