apiVersion: v1
kind: Service
metadata:
  name: custom-field-service
  namespace: bookinghub
spec:
  type: ClusterIP
  selector:
    app: custom-field-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
