apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: bookinghub
data:
  SPRING_PROFILES_ACTIVE: "production"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8080"
  RATE_LIMIT_PER_MINUTE: "120"
