apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-log-service-config
  labels:
    app: audit-log-service
data:
  SPRING_PROFILES_ACTIVE: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "audit_db"
  FLYWAY_DB_HOST: "postgres"
  FLYWAY_DB_PORT: "5432"
  FLYWAY_DB_NAME: "audit_db"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8180"
  KEYCLOAK_REALM: "bookinghub"
