apiVersion: v1
kind: Service
metadata:
  name: booking-service
  labels:
    app: booking-service
spec:
  type: ClusterIP
  selector:
    app: booking-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
