apiVersion: v1
kind: ConfigMap
metadata:
  name: locations-resources-service-config
  namespace: bookinghub
data:
  SPRING_PROFILES_ACTIVE: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "locres_db"
