apiVersion: v1
kind: Service
metadata:
  name: users-permissions-service
  namespace: bookinghub
  labels:
    app: users-permissions-service
spec:
  type: ClusterIP
  selector:
    app: users-permissions-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
    protocol: TCP
